#- name: install pycharm
#  snap:
#    name: pycharm-community
#    state: present

- name: install intellij-idea-ultimate
  snap:
    name: intellij-idea-ultimate
    state: present
    classic: true

- name: install X11 packages
  apt:
    name:
    - x11-apps
    - libxrender1
    - libxtst6
    - libxi6
    - tigervnc-standalone-server
    - tigervnc-common
    state: present

#- name: Download JB Toolbox installer
#  get_url:
#    url: https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh
#    dest: /tmp/jetbrains-toolbox.sh
#
#- name: Execute the jetbrains-toolbox.sh
#  shell: cat < /tmp/jetbrains-toolbox.sh
#
#- name: Add JB Toolbox to PATH
#  shell: export PATH=$PATH:/home/ubuntu/.local/bin

- name: install vim
  apt:
    name: "vim"
    state: present
