- name: install intellij-idea-ultimate
  snap:
    name: intellij-idea-ultimate
    state: present
    classic: true

- name: install X11 packages
  apt:
    name:
    - x11-apps
    - libxrender1
    - libxtst6
    - libxi6
    state: present

#- name: Download JB Toolbox installer
#  get_url:
#    url: https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh
#    dest: /tmp/jetbrains-toolbox.sh
#
#- name: Execute the jetbrains-toolbox.sh
#  shell: cat < /tmp/jetbrains-toolbox.sh
#
#- name: Add JB Toolbox to PATH
#  shell: export PATH=$PATH:/home/ubuntu/.local/bin

- name: install vim
  apt:
    name: "vim"
    state: present


#- name: install Mate
#  apt:
#    name:
#      - mate-core
#      - mate-desktop-environment
#      - mate-notification-daemon
#    state: present


#- name: Download Google Chrome Stable
#  shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#
#- name: Install Google Chrome Stable
#  shell: dpkg -i google-chrome-stable_current_amd64.deb
  # apt --fix-broken install

#- name: Download Google Remote Desktop
#  shell: wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb -P /tmp
#
#- name: Install Google Remote Desktop
#  shell: apt install /tmp/chrome-remote-desktop_current_amd64.deb


#- name: install VNC
#  apt:
#    name:
#      - tightvncserver
#    state: present
