---
- name: Install OpenJDK
  roles:
    - alvistack.openjdk
    - gantsign.intellij

#
#- name: install pycharm
#  snap:
#    name: pycharm-community
#    state: present

- name: install vim
  apt:
    name: "vim"
    state: present
