---
- name: install Python with dev
  apt:
    name:
      - python3-pip
      - "python{{ python_version }}"
      - "python{{ python_version }}-dev"
      - "python{{ python_version }}-venv"
    state: present


#- name: install Venv for python2
#  pip:
#    name: "virtualenv"
#    state: present