- name: apt git
  apt:
    name: "git"
    state: present

- name: install bash-git-prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    version: master
    dest: '{{ home_path }}/.bash-git-prompt'

- name: copy git-prompt config
  copy:
    src: git-prompt-colors.sh
    dest: '{{ home_path }}/.git-prompt-colors.sh'

- name: add alias pycharm
  lineinfile:
    path: "{{ user_config }}/aliases.sh"
    line: "{{ item }}"
    state: present
  with_items:
    - 'GIT_PROMPT_ONLY_IN_REPO=1'
    - 'source {{ home_path }}/.bash-git-prompt/gitprompt.sh'
    - 'GIT_PROMPT_THEME_FILE={{ home_path }}/.git-prompt-colors.sh'
    - 'GIT_PROMPT_THEME=Custom'
