---
- hosts: localhost
#  roles:
#    - alvistack.openjdk
#    - gantsign.intellij

  tasks:
    - name: Print some debug information
      vars:
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }} 
          
          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }} 
          
          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}
          
          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}
          
          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }} 

      debug:
        msg: "{{ msg.split('\n') }}"
      tags: debug_info

- import_playbook: bashrc.yml
- import_playbook: terminal.yml
- import_playbook: git.yml
- import_playbook: python.yml
- import_playbook: editors.yml
- import_playbook: projects.yml
- import_playbook: venv.yml
